CREATE TABLE itl.request (
request_id int unsigned auto_increment not null,
request_type varchar(32) not null,
user_id varchar(32) not null,
user_group varchar(50) not null,
status varchar(200) not null,
submit_timestamp timestamp not null,
start_timestamp timestamp,
end_timestamp timestamp,
template varchar(50),
vm_name varchar(16),
os varchar(32),
requested_cpu int,
requested_memory int,
requested_storage int,
product_install varchar(256),
db varchar(32),
product_upgrade varchar(256),
kb varchar(256),
fe_lcd varchar(256),
pe_lcd varchar(256),
ilog_system_rules varchar(1),
primary key (request_id)
);
